# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install maven
        run: sudo apt install maven

      - name: Clean and create package
        run: sudo mvn clean package

      - name: Install docker
        run: |
          sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install docker-ce
          sudo apt-mark hold docker-ce
          sudo systemctl status docker
          sudo usermod -aG docker $USER
      - name: Docker build
        run: |
          docker build -t docker.pkg.github.com/ties1080/actions/deploy .
      - name: Docker login
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.USER_LOGIN }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: |
          docker push docker.pkg.github.com/ties1080/actions/deploy

